apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: xyz
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xyz
  template:
    metadata:
      labels:
        app: xyz
    spec:
      containers:
      - name: todo
        image: rohanlakhani1717/todo-app:v1
        ports:
        - containerPort: 8000
        